apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    enableUserWorkload: false
    alertmanagerMain:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: {{ .Values.alertmanager.volumeClaimTemplate.spec.resources.requests.storage | default "50Gi" }}
    prometheusK8s:
      retention: {{ .Values.prometheusK8s.retention | default "7d" }}
      volumeClaimTemplate:
        metadata:
          name: prometheus-claim
        spec:
          resources:
            requests:
              storage: {{ .Values.prometheusK8s.volumeClaimTemplate.spec.resources.requests.storage | default "200Gi" }}

