global:
  singleArgoCD: false
  repoURL: https://github.com/mgamalelnaggar/ocp-hub.git
  pattern: hub
  localClusterDomain: cluster-8cgxv.8cgxv.sandbox5322.opentlc.com
  hubClusterDomain: cluster-8cgxv.8cgxv.sandbox5322.opentlc.com
  vpArgoNamespace: openshift-gitops
  secretLoader:
    disabled: True
  secretStore:
    backend: "kubernetes"
  targetRevision: main
  options:
    useCSV: True
    syncPolicy: Automatic
    installPlanApproval: Automatic
    autoApproveManualInstallPlans: false
    applicationRetryLimit: 20


