clusterGroup:
  name: hub
  targetCluster: in-cluster
  sharedValueFiles: []

  extraObjects: {}

   
    #disable-operatorhub-sources:
    #  apiVersion: config.openshift.io/v1
    #  kind: OperatorHub
    #  metadata:
    #    name: cluster
    #  spec:
    #    disableAllDefaultSources: true

############### Namespaces for Operators ######################
  namespaces:
    # Loki / Global Operators. Allnamespaces scoped operator
    - openshift-operators-redhat:
        disabled: false
        targetNamespaces: []
        labels:
          openshift.io/cluster-monitoring: "true"
    
    # UI plugin for logging. Allnamespaces scoped operator
    - openshift-cluster-observability-operator:
        disabled: false
        targetNamespaces: []
        labels:
          openshift.io/cluster-monitoring: "true"
    
    # OpenShift Data Foundation. Standard scoped operators
    - openshift-storage: 
        disabled: false
        labels:
          openshift.io/cluster-monitoring: "true"
    
    # Local Storage Operator. Standard scoped operators
    - openshift-local-storage: 
        disabled: false
        labels:
          openshift.io/cluster-monitoring: "true"

    # Quay Operator. Standard scoped operators
    - openshift-quay: 
        disabled: false
        labels:
          openshift.io/cluster-monitoring: "true"
    - quay-enterprise:
        disabled: false
        labels:
          openshift.io/cluster-monitoring: "true"    

    # RHACM Operator. Standard scoped operators
    - open-cluster-management: 
        disabled: false
        labels:
          openshift.io/cluster-monitoring: "true"

    # Logging Operator. Allnamespaces scoped operator
    - openshift-logging:
        disabled: false
        targetNamespaces: []
        labels:
          openshift.io/cluster-monitoring: "true"
    
    # NMState Operator. Standard scoped operators
    - openshift-nmstate: 
        disabled: false
        labels:
          openshift.io/cluster-monitoring: "true"

    # OSUS operator
    - openshift-update-service:
        disabled: false
        labels:
          openshift.io/cluster-monitoring: "true"

    # RHACM observability
    - open-cluster-management-observability:
        disabled: false

    # Keycloak
    - keycloak:
        disabled: false
        labels:
          openshift.io/cluster-monitoring: "true"

    # cert-manager
    - cert-manager-operator:
        disabled: false
        labels:
          openshift.io/cluster-monitoring: "true" 
#######################################################################
  operatorgroupExcludes:
    - openshift-operators
###################### Operators Subscriptions ########################
  subscriptions:

# TALM Operator
    openshift-topology-aware-lifecycle-manager:
      disabled: false
      name: topology-aware-lifecycle-manager
      namespace: openshift-operators
      channel: "stable"
      source: redhat-operators
      sourceNamespace: openshift-marketplace
      csv: update-service-operator.v5.0.3


# Update Source Operator
    openshift-update-service:
      disabled: false
      name: cincinnati-operator
      namespace: openshift-update-service
      channel: "v1"
      source: redhat-operators
      sourceNamespace: openshift-marketplace

      
# NMstate Operator    
    kubernetes-nmstate-operator:
      disabled: true
      name: kubernetes-nmstate-operator
      namespace: openshift-nmstate
      channel: "stable"
      source: redhat-operators
      sourceNamespace: openshift-marketplace

# LSO Operator
    local-storage-operator:
      disabled: true
      name: local-storage-operator
      namespace: openshift-local-storage
      channel: "stable" 
      source: redhat-operators
      sourceNamespace: openshift-marketplace


# Cluster Observability Operator. Needed mainly for Logging UI
    cluster-observability-operator:
      disabled: false
      name: cluster-observability-operator
      namespace: openshift-cluster-observability-operator
      channel: "stable"
      source: redhat-operators
      sourceNamespace: openshift-marketplace 


# All sub-ODF subscriptions for ODF operator to get installed
    odf-operator:
      disabled: true
      name: odf-operator
      namespace: openshift-storage
      channel: "stable-4.20"
      source: redhat-operators
      sourceNamespace: openshift-marketplace
      csv: odf-operator.v4.20.15-rhodf
         
# Loki Operator      
    loki-operator:
      disabled: false
      name: loki-operator
      namespace: openshift-operators-redhat
      channel: "stable-6.6"
      source: redhat-operators
      sourceNamespace: openshift-marketplace

# Logging Operator   
    logging-operator:
      disabled: false
      name: cluster-logging
      namespace: openshift-logging
      channel: "stable-6.6"
      source: redhat-operators
      sourceNamespace: openshift-marketplace
      #csv: cluster-logging.v6.4.6


# RHACM Operator
    advanced-cluster-management:
      disabled: false
      name: advanced-cluster-management
      namespace: open-cluster-management
      channel: "release-2.17"
      source: redhat-operators
      sourceNamespace: openshift-marketplace     


# Quay Operator
    quay-operator:
      disabled: true
      name: quay-operator
      namespace: openshift-operators
      source: redhat-operators
      channel: "stable-3.17"
      sourceNamespace: openshift-marketplace

# Web terminal Operator
    web-terminal-operator:
      disabled: false
      name: web-terminal
      namespace: openshift-operators
      source: redhat-operators
      channel: "fast"
      sourceNamespace: openshift-marketplace
      csv: web-terminal.v1.16.1

# keycloak Operator
    rhbk-operator:
      disabled: false
      name: rhbk-operator
      namespace: keycloak
      source: redhat-operators
      channel: "stable-v26.0"
      sourceNamespace: openshift-marketplace

# cert-manager Operator
    openshift-cert-manager-operator:
      disabled: false
      name: openshift-cert-manager-operator
      namespace: cert-manager-operator
      source: redhat-operators
      channel: "stable-v1"
      sourceNamespace: openshift-marketplace      
      
#######################  ArgoCD Applications  #####################################
  applications: 
   
    nmstate:
      disabled: false
      name: nmstate
      annotations:
        argocd.argoproj.io/sync-wave: "1"
      path: applications/nmstate
      extraValueFiles: []

    lso:
      disabled: false
      name: lso
      annotations:
        argocd.argoproj.io/sync-wave: "2"
      path: applications/lso
      extraValueFiles: []

    odf:
      disabled: false
      name: odf
      annotations:
        argocd.argoproj.io/sync-wave: "3"
      path: applications/odf
      extraValueFiles: 
        - /hub-app-values/values-odf-multus.yaml

    quay:
      disabled: false
      name: quay
      annotations:
        argocd.argoproj.io/sync-wave: "4"
      path: applications/quay
      extraValueFiles: []

    loki:
      disabled: false
      name: loki
      annotations:
        argocd.argoproj.io/sync-wave: "4"
      path: applications/loki
      extraValueFiles: []

    logging:
      disabled: false
      name: logging
      annotations:
        argocd.argoproj.io/sync-wave: "4"
      path: applications/logging
      extraValueFiles: 
        - /hub-app-values/values-logging-clf.yaml

    monitoring:
      disabled: false
      name: monitoring
      annotations:
        argocd.argoproj.io/sync-wave: "1"
      path: applications/monitoring
      extraValueFiles: []

    keycloak:
      disabled: false
      name: keycloak
      annotations:
        argocd.argoproj.io/sync-wave: "4"
      path: applications/keycloak
      extraValueFiles: []

    cert-manager:
      disabled: false
      name: cert-manager
      annotations:
        argocd.argoproj.io/sync-wave: "4"
      path: applications/cert-manager
      extraValueFiles: 
      - /hub-app-values/values-cert.yaml
      
    acm:
      disabled: false
      name: acm
      annotations:
        argocd.argoproj.io/sync-wave: "5"
      path: applications/acm
      extraValueFiles: 
      - /hub-app-values/values-acm.yaml

    ztp:
      disabled: false
      name: ztp-enabelment
      annotations:
        argocd.argoproj.io/sync-wave: "6"
      kustomize: true
      path: applications/ztp
    
    post-config:
      disabled: false
      name: post-config
      kustomize: true
      path: applications/post-config/overlays/hub01
      annotations:
        argocd.argoproj.io/sync-wave: "7"
      ignoreDifferences:
        - group: policy.open-cluster-management.io
          kind: Policy
          namespace: local-cluster
          jqPathExpressions:
            - .

#########################  ArgoCD instance  #######################################
  argoCD:
    initContainers: []
    env: []
    rbac: 
      defaultPolicy: role:readonly
      scopes: '[groups, email]'
      policy: |-
        g, system:cluster-admins, role:admin
        g, cluster-admins, role:admin
        g, admin, role:admin
        g, ocpadmin, role:admin
        #g, <username>, role:admin
    volumes: []   
    volumeMounts: []
    configManagementPlugins: []
    # resource tracking can be set to annotation, label, or annotation+label
    resourceTrackingMethod: annotation
    resourceHealthChecks:
    # [REF] https://argo-cd.readthedocs.io/en/stable/operator-manual/health/
    
      # Adding health checks to argocd to prevent pvc resources
      # that aren't bound state from blocking deployments
      # https://www.github.com/argoproj/argo-cd/issues/12840 seems to be related
    
      - kind: PersistentVolumeClaim
        check: |
          hs = {}
          if obj.status ~= nil then
            if obj.status.phase ~= nil then
              if obj.status.phase == "Pending" then
                hs.status = "Healthy"
                hs.message = obj.status.phase
                return hs
              elseif obj.status.phase == "Bound" then
                hs.status = "Healthy"
                hs.message = obj.status.phase
                return hs
              end
            end
          end
          hs.status = "Progressing"
          hs.message = "Waiting for PVC"
          return hs
      - group: policy.open-cluster-management.io
        kind: Policy
        check: |
          hs = {}
          hs.status = "Healthy"
          hs.message = "ACM Policy health check overridden"
          return hs            

    resourceActions: []
    resourceExclusions: |
      - apiGroups:
        - tekton.dev
        kinds:
        - TaskRun
        - PipelineRun
     
#############################################################################

  imperative:
    jobs: []
    image: quay.io/validatedpatterns/imperative-container:v1
    ansibleDevMode:
      enabled: false

    namespace: "imperative"
    valuesConfigMap: "helm-values-configmap"
    cronJobName: "imperative-cronjob"
    jobName: "imperative-job"
    imagePullPolicy: Always
    activeDeadlineSeconds: 60
    schedule: "*/5 * * * *"
    insecureUnsealVaultInsideClusterSchedule: "*/5 * * * *"
    verbosity: ""
    extraPlaybookArgs: []
    serviceAccountCreate: true
    serviceAccountName: imperative-sa
    clusterRoleName: imperative-cluster-role
    clusterRoleYaml: ""
    roleName: imperative-role
    roleYaml: ""
    adminServiceAccountCreate: true
    adminServiceAccountName: imperative-admin-sa
    adminClusterRoleName: imperative-admin-cluster-role
    vaultNamespace: "vault"
