clusterGroup:
  name: hub
  targetCluster: in-cluster
  sharedValueFiles: []

############### Namespaces for Operators ######################
  namespaces:
    # Loki / Global Operators
    - openshift-operators-redhat:
        targetNamespaces: []
        labels:
          openshift.io/cluster-monitoring: "true"
    
    # UI plugin for logging
    - openshift-cluster-observability-operator:
        targetNamespaces: []
        labels:
          openshift.io/cluster-monitoring: "true"
    
    # OpenShift Data Foundation
    - openshift-storage: 
        labels:
          openshift.io/cluster-monitoring: "true"
    
    # Local Storage Operator
    - openshift-local-storage: 
        labels:
          openshift.io/cluster-monitoring: "true"

    # Standard scoped operators
    - openshift-quay: 
        labels:
          openshift.io/cluster-monitoring: "true"

    # RHACM Operator
    - open-cluster-management: 
        labels:
          openshift.io/cluster-monitoring: "true"

    # Logging Operator
    - openshift-logging:
        targetNamespaces: []
        labels:
          openshift.io/cluster-monitoring: "true"
    
    # NMState Operator
    - openshift-nmstate: 
        labels:
          openshift.io/cluster-monitoring: "true"

###################### Operators Subscriptions ########################
  subscriptions:

# TALM operator
    openshift-topology-aware-lifecycle-manager:
      name: topology-aware-lifecycle-manager
      namespace: openshift-operators
      channel: "stable"
      source: redhat-operators
      sourceNamespace: openshift-marketplace
      installPlanApproval: Automatic #Manual

# NMstate Operator    
    kubernetes-nmstate-operator:
      name: kubernetes-nmstate-operator
      namespace: openshift-nmstate
      channel: "stable"
      source: redhat-operators
      sourceNamespace: openshift-marketplace
      installPlanApproval: Automatic #Manual

# LSO Operator
    local-storage-operator:
      name: local-storage-operator
      namespace: openshift-local-storage
      channel: "stable" 
      source: redhat-operators
      sourceNamespace: openshift-marketplace
      installPlanApproval: Automatic #Manual

# Cluster Observability Operator. Needed mainly for Logging UI
    cluster-observability-operator:
      name: cluster-observability-operator
      namespace: openshift-cluster-observability-operator
      channel: "stable"
      source: redhat-operators
      sourceNamespace: openshift-marketplace 
      installPlanApproval: Automatic #Manual

# All sub-ODF subscriptions for ODF operator to get installed
    odf-operator:
      name: odf-operator
      namespace: openshift-storage
      channel: "stable-4.18"
      source: redhat-operators
      sourceNamespace: openshift-marketplace
      installPlanApproval: Automatic #Manual
      
      csv: odf-operator.v4.20.13-rhodf
    
    cephcsi-operator:
      name: cephcsi-operator
      namespace: openshift-storage
      channel: "stable-4.18"
      source: redhat-operators
      sourceNamespace: openshift-marketplace
      installPlanApproval: Automatic #Manual
    mcg-operator:
      name: mcg-operator
      namespace: openshift-storage
      channel: "stable-4.18"
      source: redhat-operators
      sourceNamespace: openshift-marketplace
      installPlanApproval: Automatic #Manual
    ocs-client-operator:
      name: ocs-client-operator
      namespace: openshift-storage
      channel: "stable-4.18"
      source: redhat-operators
      sourceNamespace: openshift-marketplace   
      installPlanApproval: Automatic #Manual
    ocs-operator:
      name: ocs-operator
      namespace: openshift-storage
      channel: "stable-4.18"
      source: redhat-operators
      sourceNamespace: openshift-marketplace 
      installPlanApproval: Automatic #Manual
    odf-csi-addons-operator:
      name: odf-csi-addons-operator
      namespace: openshift-storage
      channel: "stable-4.18"
      source: redhat-operators
      sourceNamespace: openshift-marketplace  
      installPlanApproval: Automatic #Manual
    odf-dependencies:
      name: odf-dependencies
      namespace: openshift-storage
      channel: "stable-4.18"
      source: redhat-operators
      sourceNamespace: openshift-marketplace 
      installPlanApproval: Automatic #Manual
    odf-prometheus-operator:
      name: odf-prometheus-operator
      namespace: openshift-storage
      channel: "stable-4.18"
      source: redhat-operators
      sourceNamespace: openshift-marketplace 
      installPlanApproval: Automatic #Manual
      
# Loki Operator      
    loki-operator:
      name: loki-operator
      namespace: openshift-operators-redhat
      channel: "stable-6.4"
      source: redhat-operators
      sourceNamespace: openshift-marketplace

# Logging Operator   
    logging-operator:
      name: cluster-logging
      namespace: openshift-logging
      channel: "stable-6.4"
      source: redhat-operators
      sourceNamespace: openshift-marketplace
#      csv: cluster-logging.v6.4.6
      installPlanApproval: Automatic #Manual

# RHACM Operator
    advanced-cluster-management:
      name: advanced-cluster-management
      namespace: open-cluster-management
      channel: "release-2.16"
      source: redhat-operators
      sourceNamespace: openshift-marketplace     
      installPlanApproval: Automatic #Manual

# Quay Operator
    quay-operator:
      name: quay-operator
      namespace: openshift-operators
      source: redhat-operators
      channel: "stable-3.17"
      sourceNamespace: openshift-marketplace     
      installPlanApproval: Automatic #Manual
#######################  ArgoCD Applications  #####################################
  applications: 
    nmstate:
      disabled: false
      name: nmstate
      namespace: default
      path: applications/nmstate
      extraValueFiles: []

    lso:
      disabled: false
      name: lso
      namespace: default
      path: applications/lso
      extraValueFiles: []

    odf:
      disabled: false
      name: odf
      namespace: default
      path: applications/odf
      extraValueFiles: []


    acm:
      disabled: false
      name: acm
      namespace: default
      path: applications/acm
      extraValueFiles: []

    quay:
      disabled: false
      name: quay
      namespace: default
      path: applications/quay
      extraValueFiles: []

    loki:
      disabled: false
      name: loki
      namespace: default
      path: applications/loki
      extraValueFiles: []

    logging:
      disabled: false
      name: logging
      namespace: default
      path: applications/logging
      extraValueFiles: []

    monitoring:
      disabled: false
      name: monitoring
      namespace: default
      path: applications/monitoring
      extraValueFiles: []

#########################  ArgoCD instance  #######################################
  argoCD:
    initContainers: []
    env: []
    rbac: {}
    volumes: []
    volumeMounts: []
    configManagementPlugins: []
    # resource tracking can be set to annotation, label, or annotation+label
    resourceTrackingMethod: annotation
    resourceHealthChecks:
      # Adding health checks to argocd to prevent pvc resources
      # that aren't bound state from blocking deployments
      # https://www.github.com/argoproj/argo-cd/issues/12840 seems to be related
      - kind: PersistentVolumeClaim
        check: |
          hs = {}
          if obj.status ~= nil then
            if obj.status.phase ~= nil then
              if obj.status.phase == "Pending" then
                hs.status = "Healthy"
                hs.message = obj.status.phase
                return hs
              elseif obj.status.phase == "Bound" then
                hs.status = "Healthy"
                hs.message = obj.status.phase
                return hs
              end
            end
          end
          hs.status = "Progressing"
          hs.message = "Waiting for PVC"
          return hs

    resourceActions: []
    resourceExclusions: |
      - apiGroups:
        - tekton.dev
        kinds:
        - TaskRun
        - PipelineRun
        
#############################################################################

  imperative:
    jobs: []
    image: quay.io/validatedpatterns/imperative-container:v1
    ansibleDevMode:
      enabled: false

    namespace: "imperative"
    valuesConfigMap: "helm-values-configmap"
    cronJobName: "imperative-cronjob"
    jobName: "imperative-job"
    imagePullPolicy: Always
    activeDeadlineSeconds: 60
    schedule: "*/5 * * * *"
    insecureUnsealVaultInsideClusterSchedule: "*/5 * * * *"
    verbosity: ""
    extraPlaybookArgs: []
    serviceAccountCreate: true
    serviceAccountName: imperative-sa
    clusterRoleName: imperative-cluster-role
    clusterRoleYaml: ""
    roleName: imperative-role
    roleYaml: ""
    adminServiceAccountCreate: true
    adminServiceAccountName: imperative-admin-sa
    adminClusterRoleName: imperative-admin-cluster-role
    vaultNamespace: "vault"
