global:
  singleArgoCD: false
  repoURL: https://github.com/mgamalelnaggar/ocp-hub.git
  pattern: hub
  localClusterDomain: snomgdcluster01.localdomain
  hubClusterDomain: snomgdcluster01.localdomain
  vpArgoNamespace: openshift-gitops
  secretLoader:
    disabled: True
  secretStore:
    backend: "kubernetes"
  targetRevision: main
  options:
    useCSV: True
    syncPolicy: Automatic
    installPlanApproval: Automatic
    autoApproveManualInstallPlans: True
    applicationRetryLimit: 20

clusterGroup:
  name: hub
  targetCluster: in-cluster
  sharedValueFiles: []

############### Namespaces for Operators ######################
  namespaces:
    # Loki / Global Operators
    - openshift-operators-redhat:
        targetNamespaces: []
    
    # UI plugin for logging
    - openshift-cluster-observability-operator:
        targetNamespaces: []
    
    # OpenShift Data Foundation
    - openshift-storage: {}
    
    # Local Storage Operator
    - openshift-local-storage: {}

    # Standard scoped operators
    - openshift-quay: {}

    - open-cluster-management: {}

    - openshift-logging:
        targetNamespaces: []
    
    - openshift-nmstate: {}

    - openshift-cluster-observability-operator:
        targetNamespaces: []

###################### Operators Subscriptions ########################
  subscriptions:

    kubernetes-nmstate-operator:
      name: kubernetes-nmstate-operator
      namespace: openshift-nmstate
      channel: "stable"
      source: redhat-operators
      sourceNamespace: openshift-marketplace

    local-storage-operator:
      name: local-storage-operator
      namespace: openshift-local-storage
      channel: "stable" 
      source: redhat-operators
      sourceNamespace: openshift-marketplace

    cluster-observability-operator:
      name: cluster-observability-operator
      namespace: openshift-cluster-observability-operator
      channel: "stable"
      source: redhat-operators
      sourceNamespace: openshift-marketplace 
      
    loki-operator:
      name: loki-operator
      namespace: openshift-operators-redhat
      channel: "stable-6.4"
      source: redhat-operators
      sourceNamespace: openshift-marketplace

   
    logging-operator:
      name: cluster-logging
      namespace: openshift-logging
      channel: "stable-6.4"
      source: redhat-operators
      sourceNamespace: openshift-marketplace
#      csv: cluster-logging.v6.4.6

     
      
#######################  ArgoCD Applications  #####################################
  applications: 
    nmstate:
      name: nmstate
      namespace: default
      path: applications/nmstate

    lso:
      name: lso
      namespace: default
      path: applications/lso

#    odf:
#      name: odf
#      namespace: default
#      path: applications/odf
#      extraValueFiles:
#        - $patternref/hub01-values-files/values-odf-hub01.yaml

#    acm:
#      name: acm
#      namespace: default
#      path: applications/acm

#    quay:
#      name: quay
#      namespace: default
#      path: applications/quay

#    loki:
#      name: loki
#      namespace: default
#      path: applications/loki

#    logging:
#      name: logging
#      namespace: default
#      path: applications/logging

#    monitoring:
#      name: monitoring
#      namespace: default
#      path: applications/monitoring

#########################  ArgoCD instance  #######################################
  argoCD:
    initContainers: []
    env: []
    rbac: {}
    volumes: []
    volumeMounts: []
    configManagementPlugins: []
    # resource tracking can be set to annotation, label, or annotation+label
    resourceTrackingMethod: annotation
    resourceHealthChecks:
      # Adding health checks to argocd to prevent pvc resources
      # that aren't bound state from blocking deployments
      # https://www.github.com/argoproj/argo-cd/issues/12840 seems to be related
      - kind: PersistentVolumeClaim
        check: |
          hs = {}
          if obj.status ~= nil then
            if obj.status.phase ~= nil then
              if obj.status.phase == "Pending" then
                hs.status = "Healthy"
                hs.message = obj.status.phase
                return hs
              elseif obj.status.phase == "Bound" then
                hs.status = "Healthy"
                hs.message = obj.status.phase
                return hs
              end
            end
          end
          hs.status = "Progressing"
          hs.message = "Waiting for PVC"
          return hs

    resourceActions: []
    resourceExclusions: |
      - apiGroups:
        - tekton.dev
        kinds:
        - TaskRun
        - PipelineRun
        
#############################################################################

  imperative:
    jobs: []
    image: quay.io/validatedpatterns/imperative-container:v1
    ansibleDevMode:
      enabled: false

    namespace: "imperative"
    valuesConfigMap: "helm-values-configmap"
    cronJobName: "imperative-cronjob"
    jobName: "imperative-job"
    imagePullPolicy: Always
    activeDeadlineSeconds: 60
    schedule: "*/5 * * * *"
    insecureUnsealVaultInsideClusterSchedule: "*/5 * * * *"
    verbosity: ""
    extraPlaybookArgs: []
    serviceAccountCreate: true
    serviceAccountName: imperative-sa
    clusterRoleName: imperative-cluster-role
    clusterRoleYaml: ""
    roleName: imperative-role
    roleYaml: ""
    adminServiceAccountCreate: true
    adminServiceAccountName: imperative-admin-sa
    adminClusterRoleName: imperative-admin-cluster-role
    vaultNamespace: "vault"
