clusterGroup:
  namespaces:
    - openshift-logging:
        targetNamespaces: []
  subscriptions:
   logging-operator:
      name: logging-operator
      namespace: openshift-logging
      channel: "stable-6.4"
      source: redhat-operators
      sourceNamespace: openshift-marketplace     
