global:
  singleArgoCD: false
  repoURL: https://github.com/mgamalelnaggar/ocp-hub.git
  extraValueFiles: 
    - values-hub.yaml
  pattern: hub
  localClusterDomain: snomgdcluster01.localdomain
  hubClusterDomain: snomgdcluster01.localdomain
  vpArgoNamespace: openshift-gitops
  secretLoader:
    disabled: true
  secretStore:
    backend: "kubernetes"
  targetRevision: main
  options:
    useCSV: true
    syncPolicy: Automatic
    installPlanApproval: Automatic
    autoApproveManualInstallPlans: true
    applicationRetryLimit: 20
