global:
  singleArgoCD: false
  extraValueFiles: []
  pattern: hub
  localClusterDomain: "snomgdcluster01.localdomain"
  hubClusterDomain: "snomgdcluster01.localdomain"
  vpArgoNamespace: openshift-gitops
  secretLoader:
    disabled: true
  secretStore:
    backend: "kubernetes"
  targetRevision: main
  Options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic
    applicationRetryLimit: 20

main:
  clusterGroupName: hub
  multiSourceConfig:
    enabled: false
    clusterGroupChartVersion: "0.9.*"
