---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: olm-installer-sa
  namespace: openshift-nmstate
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: olm-installer-sa
  namespace: openshift-local-storage
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: olm-installer-sa
  namespace: openshift-storage
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: olm-installer-sa
  namespace: open-cluster-management
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: olm-installer-sa
  namespace: openshift-operators
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: olmv1-infrastructure-installers
subjects:
- kind: ServiceAccount
  name: olm-installer-sa
  namespace: openshift-nmstate
- kind: ServiceAccount
  name: olm-installer-sa
  namespace: openshift-local-storage
- kind: ServiceAccount
  name: olm-installer-sa
  namespace: openshift-storage
- kind: ServiceAccount
  name: olm-installer-sa
  namespace: open-cluster-management
- kind: ServiceAccount
  name: olm-installer-sa
  namespace: openshift-operators
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
