apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - etcd-bkp-ns.yaml
  - placement-local-hub.yaml
  - placementbinding.yaml
  - policy-ocp-etcd-backup.yaml
  #- policy-identity-providers.yaml
  - policy-ingress-replicas.yaml
  - policy-console-plugins.yaml
  - policy-etcd-encryption.yaml
  - policy-whereabouts-config.yaml
  #- policy-master-kubeletconfig.yaml
  - policy-core-pass.yaml
  - policy-patch-cluster-certs.yaml
  - policy-identity-providers-keycloak.yaml

