# This policy should be kept inform. Applying kubeletconfig triggeres node reboot
# If you need to enforce it, do the action from RHACM, and then the policy will revert back to inform after applying the change.
# This to control nodes reboots and avoid any unexpected disruptions

apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-master-kubeletconfig
  namespace: open-cluster-management-policies
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: config-master-kubeletconfig
        spec:
          remediationAction: enforce
          severity: medium
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: machineconfiguration.openshift.io/v1
                kind: KubeletConfig
                metadata:
                  name: master-garbagecollection-kubeconfig
                spec:
                  machineConfigPoolSelector:
                    matchLabels:
                      pools.operator.machineconfiguration.openshift.io/master: ""
                  autoSizingReserved: true
                  kubeletConfig:
                    evictionSoft:
                      memory.available: "500Mi"
                      nodefs.available: "10%"
                      nodefs.inodesFree: "5%"
                      imagefs.available: "15%"
                      imagefs.inodesFree: "10%"
                    evictionSoftGracePeriod:
                      memory.available: "1m30s"
                      nodefs.available: "1m30s"
                      nodefs.inodesFree: "1m30s"
                      imagefs.available: "1m30s"
                      imagefs.inodesFree: "1m30s"
                    evictionHard:
                      memory.available: "200Mi"
                      nodefs.available: "5%"
                      nodefs.inodesFree: "4%"
                      imagefs.available: "10%"
                      imagefs.inodesFree: "5%"
                    evictionPressureTransitionPeriod: "3m"
                    imageMinimumGCAge: "5m"
                    imageGCHighThresholdPercent: 80
                    imageGCLowThresholdPercent: 75
