apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-htpasswd-idp
  namespace: open-cluster-management-policies
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: config-htpasswd-idp
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: htpasswd-secret
                  namespace: openshift-config
                type: Opaque
                data:
                  htpasswd: b2NwYWRtaW46JDJ5JDA1JFIzUnA0dC41eExGMHJ5U1VtZ0NyYy5zbGRiM2tnVzA5elQyQkQ2N3hKWUY1NVFKVlJaQjhlCg==          
            - complianceType: musthave
              objectDefinition:
                apiVersion: config.openshift.io/v1
                kind: OAuth
                metadata:
                  name: cluster
                spec:
                  identityProviders:
                    - name: htpasswd-provider
                      mappingMethod: claim
                      type: HTPasswd
                      htpasswd:
                        fileData:
                          name: htpasswd-secret
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: ClusterRoleBinding
                metadata:
                  name: ocpadmin-cluster-admin
                subjects:
                  - kind: User
                    name: ocpadmin
                    apiGroup: rbac.authorization.k8s.io
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: cluster-admin
