apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-ldap-sync
  namespace: open-cluster-management-policies
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: configure-ldap-sync
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            {{ if eq (fromConfigMap "default" "ldap-config" "ldap" "") "enabled" }}

            # 1. Namespace
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: ldap-sync

            # 2. ServiceAccount
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: ServiceAccount
                metadata:
                  name: ldap-group-syncer
                  namespace: ldap-sync

            # 3. ClusterRole
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: ClusterRole
                metadata:
                  name: ldap-group-syncer
                rules:
                  - apiGroups:
                      - user.openshift.io
                    resources:
                      - groups
                    verbs:
                      - get
                      - list
                      - create
                      - update

            # 4. ClusterRoleBinding
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: ClusterRoleBinding
                metadata:
                  name: ldap-group-syncer
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: ldap-group-syncer
                subjects:
                  - kind: ServiceAccount
                    name: ldap-group-syncer
                    namespace: ldap-sync

            # 5. Bind Password Secret
            {{ if ne (fromConfigMap "default" "ldap-config" "bindPassword" "") "" }}
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: ldap-secret
                  namespace: ldap-sync
                type: Opaque
                stringData:
                  bindPassword: '{{ (fromConfigMap "default" "ldap-config" "bindPassword" "") }}'
            {{ end }}

            # 6. LDAP CA ConfigMap
            {{ if eq (fromConfigMap "default" "ldap-config" "secure" "") "true" }}
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: ConfigMap
                metadata:
                  name: ldap-ca
                  namespace: ldap-sync
                data:
                  ca.crt: '{{ (fromConfigMap "default" "ldap-config" "ldap-ca" "") }}'
            {{ end }}

            # 7. LDAP Sync ConfigMap (ActiveDirectory Schema)
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: ConfigMap
                metadata:
                  name: ldap-group-syncer
                  namespace: ldap-sync
                data:
                  sync.yaml: |
                    kind: LDAPSyncConfig
                    apiVersion: v1
                    url: '{{ (fromConfigMap "default" "ldap-config" "url" "") }}'
                    bindDN: '{{ (fromConfigMap "default" "ldap-config" "bindDN" "") }}'
                    bindPassword:
                      file: "/etc/secrets/bindPassword"
                    insecure: {{ if eq (fromConfigMap "default" "ldap-config" "secure" "") "true" }}false{{ else }}true{{ end }}
                    {{ if eq (fromConfigMap "default" "ldap-config" "secure" "") "true" }}
                    ca: /etc/ldap-ca/ca.crt
                    {{ end }}
                    activeDirectory:
                      usersQuery:
                        baseDN: "ou=users,dc=example,dc=com"
                        scope: sub
                        derefAliases: never
                        filter: (objectclass=person)
                        pageSize: 0
                      userNameAttributes: [ sAMAccountName ]
                      groupMembershipAttributes: [ memberOf ]

            # 8. CronJob
            - complianceType: musthave
              objectDefinition:
                apiVersion: batch/v1
                kind: CronJob
                metadata:
                  name: ldap-group-syncer
                  namespace: ldap-sync
                spec:
                  schedule: "*/30 * * * *"
                  concurrencyPolicy: Forbid
                  jobTemplate:
                    spec:
                      backoffLimit: 0
                      ttlSecondsAfterFinished: 1800
                      template:
                        spec:
                          serviceAccountName: ldap-group-syncer
                          restartPolicy: Never
                          containers:
                            - name: ldap-group-sync
                              image: "registry.redhat.io/openshift4/ose-cli:latest"
                              command:
                                - "/bin/bash"
                                - "-c"
                                - "oc adm groups sync --sync-config=/etc/config/sync.yaml --confirm"
                              volumeMounts:
                                - mountPath: "/etc/config"
                                  name: "ldap-sync-volume"
                                - mountPath: "/etc/secrets"
                                  name: "ldap-bind-password"
                                {{ if eq (fromConfigMap "default" "ldap-config" "secure" "") "true" }}
                                - mountPath: "/etc/ldap-ca"
                                  name: "ldap-ca"
                                {{ end }}
                          volumes:
                            - name: "ldap-sync-volume"
                              configMap:
                                name: "ldap-group-syncer"
                            - name: "ldap-bind-password"
                              secret:
                                secretName: "ldap-secret"
                            {{ if eq (fromConfigMap "default" "ldap-config" "secure" "") "true" }}
                            - name: "ldap-ca"
                              configMap:
                                name: "ldap-ca"
                            {{ end }}
            {{ end }}
