apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-patch-cluster-certs
  namespace: open-cluster-management-policies
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: patch-ingress-and-api-certs
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            # 1. Patch IngressController
            - complianceType: musthave
              objectDefinition:
                apiVersion: operator.openshift.io/v1
                kind: IngressController
                metadata:
                  name: default
                  namespace: openshift-ingress-operator
                spec:
                  defaultCertificate:
                    name: hub-ingress-cert

            # 2. Patch APIServer
            - complianceType: musthave
              objectDefinition:
                apiVersion: config.openshift.io/v1
                kind: APIServer
                metadata:
                  name: cluster
                spec:
                  namedCertificates:
                    - names:
                        - '{{ hub (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.apiServerURL | trimPrefix "https://" | trimSuffix ":6443" hub }}'
                      servingCertificate:
                        name: hub-api-cert
