apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-identity-providers
  namespace: open-cluster-management-policies
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: configure-identity-providers
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: htpasswd-secret
                  namespace: openshift-config
                type: Opaque
                data:
                  htpasswd: b2NwYWRtaW46JDJ5JDA1JFIzUnA0dC41eExGMHJ5U1VtZ0NyYy5zbGRiM2tnVzA5elQyQkQ2N3hKWUY1NVFKVlJaQjhlCg==
            {{ if eq (fromConfigMap "default" "enable-ldap" "ldap") "enabled" }}
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: ldap-provider-secret
                  namespace: openshift-config
                type: Opaque
                stringData:
                  bindPassword: '{{ (fromConfigMap "default" "enable-ldap" "bind-password") }}'
            {{ if eq (fromConfigMap "default" "enable-ldap" "secure") "true" }}      
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1     
                kind: ConfigMap
                metadata:
                  name: ldap-ca-cm
                  namespace: openshift-config
                data:
                  ca.crt: '{{ (fromConfigMap "default" "enable-ldap" "ldap-ca") }}'
            {{ end }}
            {{ end }}
            - complianceType: musthave
              objectDefinition:
                apiVersion: config.openshift.io/v1
                kind: OAuth
                metadata:
                  name: cluster
                spec:
                  identityProviders:
                    - name: htpasswd-provider
                      mappingMethod: claim
                      type: HTPasswd
                      htpasswd:
                        fileData:
                          name: htpasswd-secret
                     {{ if eq (fromConfigMap "default" "enable-ldap" "ldap") "enabled" }}  
                    - name: ldapidp
                      mappingMethod: claim
                      type: LDAP
                      ldap:
                        attributes:
                          id:
                            - dn
                          email:
                            - mail
                          name:
                            - cn
                          preferredUsername:
                            - uid
                        bindDN: '{{ (fromConfigMap "default" "enable-ldap" "bindDN") }}'
                        bindPassword:
                          name: ldap-provider-secret
                        {{ if eq (fromConfigMap "default" "enable-ldap" "secure") "true" }}
                        ca:
                          name: ldap-ca-cm
                        {{ end }}
                        insecure: {{ if eq (fromConfigMap "default" "enable-ldap" "secure") "true" }}false{{else}}true{{ end }}
                        url: '{{ (fromConfigMap "default" "enable-ldap" "url") }}'
                     {{ end }}
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: ClusterRoleBinding
                metadata:
                  name: ocpadmin-cluster-admin
                subjects:
                  - kind: User
                    name: ocpadmin
                    apiGroup: rbac.authorization.k8s.io
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: cluster-admin
