{{- if $.Values.global.singleArgoCD }}
{{- else }}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: {{ $.Values.global.pattern }}-{{ .Values.clusterGroup.name }}
  name: {{ $.Values.global.pattern }}-{{ .Values.clusterGroup.name }}
spec: {}
{{- end }}{{- /* if .singleArgoCD */}}
