apiVersion: v1
kind: Secret
metadata:
  name: vfe-ca-secret
  namespace: cert-manager
type: kubernetes.io/tls
data:
# cat ca.crt | base64 -w0
  tls.crt: <BASE64_ENCODED_CA_CERT>
  tls.key: <BASE64_ENCODED_CA_KEY>
