apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hub-ingress-cert
  namespace: openshift-ingress
spec:
  secretName: hub-ingress-cert-secret
  issuerRef:
    name: vodafone-ca-issuer
    kind: ClusterIssuer
  commonName: "*.apps.{{ .Values.global.hubClusterDomain }}"
  dnsNames:
    - "*.apps.{{ .Values.global.hubClusterDomain }}"
