apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-ocp-etcd-backup
  namespace: open-cluster-management-policies
placementRef:
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
  name: placement-local-hub
subjects:
  - apiGroup: policy.open-cluster-management.io
    kind: Policy
    name: policy-ocp-etcd-backup
  - apiGroup: policy.open-cluster-management.io
    kind: Policy
    name: policy-htpasswd-idp
  - apiGroup: policy.open-cluster-management.io
    kind: Policy
    name: policy-ingress-replicas
  - apiGroup: policy.open-cluster-management.io
    kind: Policy
    name: policy-console-plugins
  - apiGroup: policy.open-cluster-management.io
    kind: Policy
    name: policy-etcd-encryption
  - apiGroup: policy.open-cluster-management.io
    kind: Policy
    name: 
  - apiGroup: policy.open-cluster-management.io
    kind: Policy
    name: 
  - apiGroup: policy.open-cluster-management.io
    kind: Policy
    name: 
  - apiGroup: policy.open-cluster-management.io
    kind: Policy
    name: 
