apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-console-plugins
  namespace: open-cluster-management-policies
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: config-console-plugins
        spec:
          remediationAction: enforce
          severity: medium
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operator.openshift.io/v1
                kind: Console
                metadata:
                  name: cluster
                spec:
                  plugins:
                    - monitoring-plugin
                    - networking-console-plugin
                    - nmstate-console-plugin
                    - odf-console
                    - logging-view-plugin
