apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: logging-loki 
  namespace: openshift-logging
spec:
  limits:
    global:
      retention:
        days: {{ .Values.loki.limits.global.retention.days | default '10' }}
    tenants:
      application:
        retention:
          days: { .Values.loki.limits.tenants.application.retention.days | default '3' }}
      audit:
        retention:
          days: { .Values.loki.limits.tenants.audit.retention.days | default '7' }}
      infrastructure:
        retention:
          days: { .Values.loki.limits.tenants.infrastructure.retention.days | default '7' }}
  size: {{ .Values.loki.size }} 
  storage:
    schemas:
      - effectiveDate: '2023-10-15'
        version: v13
    secret:
      name: {{ index .Values.loki."s3-secret-name" }}
      type: s3
    tls:
      caName: openshift-service-ca.crt
  storageClassName: {{ index .Values.loki."storage-class-name" }}
  template: {}
  tenants:
    mode: openshift-logging
