---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki-sa
  namespace: openshift-logging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: loki-tmp-cluster-role
rules:
  - apiGroups:
    - '*'
    resources:
    - '*'
    verbs:
    - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: loki-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: loki-tmp-cluster-role
subjects:
  - kind: ServiceAccount
    name: loki-sa
    namespace: openshift-logging
