apiVersion: k8s.keycloak.org/v2beta1
kind: Keycloak
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  name: {{ .Values.clusterGroup.name }}-keycloack
  namespace: keycloak
spec:
  instances: 1
  db:
    vendor: postgres
    host: postgres-db
    usernameSecret:
      name: keycloak-pgsql-user
      key: username
    passwordSecret:
      name: keycloak-pgsql-user
      key: password
  hostname:
    hostname: sso-{{ .Values.clusterGroup.name }}.{{ .Values.global.hubClusterDomain }}
  http:
    tlsSecret: keycloak-tls
  ingress:
    className: openshift-default
  instances: 1
  proxy:
    headers: xforwarded
  additionalOptions:
    - name: http-relative-path
      value: /auth  
