apiVersion: k8s.keycloak.org/v2beta1
kind: Keycloak
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  name: {{ .Values.clusterGroup.name }}-keycloak
  namespace: keycloak
spec:
  instances: 1
  db:
    vendor: postgres
    host: postgres-db
    usernameSecret:
      name: keycloak-pgsql-user
      key: username
    passwordSecret:
      name: keycloak-pgsql-user
      key: password
  hostname:
    hostname: sso.{{ .Values.global.hubClusterDomain }}
  http:
    httpEnabled: true
  ingress:
    className: openshift-default
  proxy:
    headers: xforwarded
