apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "8"
  name: keycloak-link
  namespace: keycloak
spec:
  applicationMenu:
    section: Red Hat applications
    imageURL: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMDI0IDEwMjQiPjxwYXRoIGZpbGw9IiM0MDlCREIiIGQ9Ik03ODYuMiAzOTUuNWgtODAuNmMtMS41IDAtMy0uOC0zLjctMi4xbC02NC43LTExMi4yYy0uOC0xLjMtMi4yLTIuMS0zLjgtMi4xaC0yNjRjLTEuNSAwLTMgLjgtMy43IDIuMWwtNjcuMyAxMTYuNC02NC44IDExMi4yYy0uNyAxLjMtLjcgMi45IDAgNC4zbDY0LjggMTEyLjIgNjcuMiAxMTYuNWMuNyAxLjMgMi4yIDIuMiAzLjcgMi4xaDI2NC4xYzEuNSAwIDMtLjggMy44LTIuMUw3MDIgNjMwLjZjLjctMS4zIDIuMi0yLjIgMy43LTIuMWg4MC42YzIuNyAwIDQuOC0yLjIgNC44LTQuOFY0MDAuNGMtLjEtMi43LTIuMy00LjktNC45LTQuOXpNNDc3LjUgNzM1LjFjLTEyMi45IDAtMjIyLjktMTAwLTIyMi45LTIyMi45czEwMC0yMjIuOSAyMjIuOS0yMjIuOSAyMjIuOSAxMDAgMjIyLjkgMjIyLjktMTAwIDIyMi45LTIyMi45IDIyMi45eiIvPjxwYXRoIGZpbGw9IiMxQTI1MkMiIGQ9Ik00NzcuNSAzNTIuNWMtODguMSAwLTE1OS43IDcxLjYtMTU5LjcgMTU5LjdzNzEuNiAxNTkuNyAxNTkuNyAxNTkuNyAxNTkuNy03MS42IDE1OS43LTE1OS43LTcxLjYtMTU5LjctMTU5LjctMTU5Ljd6bTAgMjU2LjRjLTUzLjQgMC05Ni43LTQzLjMtOTYuNy05Ni43czQzLjMtOTYuNyA5Ni43LTk2LjcgOTYuNyA0My4zIDk2LjcgOTYuNy00My4zIDk2LjctOTYuNyA5Ni43eiIvPjwvc3ZnPg=="
  href: 'https://sso.{{ .Values.global.hubClusterDomain }}'
  location: ApplicationMenu
  text: 'Red Hat Build of Keycloak'
