apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  annotations:
    
  name: keycloak-link
  namespace: keycloak
spec:
  applicationMenu:
    section: Red Hat applications
    imageURL: 'https://upload.wikimedia.org/wikipedia/commons/3/3a/OpenShift-LogoType.svg'
  href: 'https://sso.{{ .Values.global.hubClusterDomain }}'
  location: ApplicationMenu
  text: 'Red Hat Build of Keycloak'
