apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: keycloak-db-secret
  namespace: keycloack
type: Opaque
data:
  username: "db-user"
  password: "Hb8AtsZihw3c1VhYFg6R"
