apiVersion: k8s.keycloak.org/v2beta1
kind: Keycloak
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  name: {{ .Values.clusterGroup.name }}-keycloack
  namespace: {{ .Values.keycloak.namespace }}
spec:
  instances: 1
  db:
    vendor: postgres
    host: postgres-db
    usernameSecret:
      name: keycloak-pgsql-user
      key: username
    passwordSecret:
      name: keycloak-pgsql-user
      key: password
  hostname:
    hostname: sso.{{ .Values.global.hubClusterDomain }}
    strict: false
    strictBackchannel: false
  http:
    httpEnabled: false
    tlsSecret: keycloak-tls
  ingress:
    enabled: false
  instances: 1
  transaction:
    xaEnabled: true
  
  ingress:
    className: openshift-default
    tlsSecret: keycloak-tls-secret
  http:
    httpEnabled: true
  additionalOptions:
    - name: enable-recovery
      value: 'true'
