apiVersion: k8s.keycloak.org/v2beta1
kind: Keycloak
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  name: {{ .Values.global.hubClusterDomain }}-keycloack
  namespace: {{ .Values.keycloak.namespace }}
spec:
  instances: 1
  db:
    vendor: postgres
    host: postgres-db
    usernameSecret:
      name: keycloak-db-secret
      key: username
    passwordSecret:
      name: keycloak-db-secret
      key: password
  ingress:
    className: openshift-default
    tlsSecret: keycloak-tls-secret
  http:
    httpEnabled: true

