apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  name: ztp-argocd
  namespace: openshift-gitops
spec:
  kustomizeBuildOptions: "--enable-alpha-plugins"
  repo: 
    volumes:
      - name: kustomize
        emptyDir: {}
    initContainers: 
      - name: kustomize-plugin
        image: "registry.redhat.io/openshift4/ztp-site-generate-rhel9:v4.20"
        command: ["/exportkustomize.sh"]
        args: ["/.config"]
        volumeMounts:
          - name: kustomize
            mountPath: /.config
      - name: policy-generator-install
        image: "registry.redhat.io/rhacm2/multicluster-operators-subscription-rhel9:v2.17"
        command: ["/bin/bash"]
        args:
          - "-c"
          - "mkdir -p /.config/kustomize/plugin/policy.open-cluster-management.io/v1/policygenerator && cp /policy-generator/PolicyGenerator-not-fips-compliant /.config/kustomize/plugin/policy.open-cluster-management.io/v1/policygenerator/PolicyGenerator"
        volumeMounts:
          - name: kustomize
            mountPath: /.config
