apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: openshift-gitops
  namespace: openshift-gitops
#spec:
#  kustomizeBuildOptions: "--enable-alpha-plugins"
#  repo: 
#    volumes:
#      - name: kustomize
#        emptyDir: {}
#    initContainers: 
#      - name: ztp-site-generate
#        image: "registry.redhat.io/openshift4/ztp-site-generate-rhel8:v4.21"
#        command: ["/exportkustomize.sh"]
#        args: ["/.config"]
#        volumeMounts:
#          - name: kustomize
#            mountPath: /.config
#      - name: policy-generator-install
#        image: "registry.redhat.io/rhacm2/multicluster-operators-subscription-rhel9:v2.17"
#        command: ["/bin/bash"]
#        args:
#          - "-c"
#          - "mkdir -p /.config/kustomize/plugin/policy.open-cluster-management.io/v1/policygenerator && cp /policy-generator/PolicyGenerator-not-fips-compliant /.config/kustomize/plugin/policy.open-cluster-management.io/v1/policygenerator/PolicyGenerator"
#        volumeMounts:
#          - name: kustomize
#           mountPath: /.config
