apiVersion: search.open-cluster-management.io/v1alpha1
kind: Search
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    cluster.open-cluster-management.io/backup: ""
  name: search-v2-operator
  namespace: open-cluster-management    
spec:
  dbStorage:
    size: 10Gi
    storageClassName: ocs-storagecluster-ceph-rbd  
