{{- if .Values.acm.observability.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: thanos-tmp-sa
  namespace: open-cluster-management-observability
  annotations:
    argocd.argoproj.io/sync-wave: "8"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: thanos-tmp-cluster-role
  annotations:
    argocd.argoproj.io/sync-wave: "8"  
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: thanos-tmp-cluster-rolebinding
  annotations:
    argocd.argoproj.io/sync-wave: "8"  
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: thanos-tmp-cluster-role
subjects:
  - kind: ServiceAccount
    name: thanos-tmp-sa
    namespace: open-cluster-management-observability
{{- end }}
