{{- if .Values.acm.observability.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: copy-pull-secret
  namespace: open-cluster-management-observability
  annotations:
    argocd.argoproj.io/sync-wave: "8"
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
data:
  copy-pull-secret.sh: |
    #!/usr/bin/env bash
    set -eo pipefail

    NAMESPACE="open-cluster-management-observability"
    TARGET_SECRET_NAME="multiclusterhub-operator-pull-secret"
    DOCKER_CONFIG_JSON=`oc extract secret/pull-secret -n openshift-config --to=-`

    # 1. Check if the target secret already exists
    if oc get secret "${TARGET_SECRET_NAME}" -n "${NAMESPACE}" &>/dev/null; then
      echo "Secret '${TARGET_SECRET_NAME}' already exists in namespace '${NAMESPACE}'. Skipping creation."
      exit 0
    fi

    echo "Secret '${TARGET_SECRET_NAME}' not found. Creating the secret..."

    # 2. Create the Secret
    echo "Creating secret ${TARGET_SECRET_NAME} in namespace ${NAMESPACE}..."
    oc create secret generic "${TARGET_SECRET_NAME}" -n "${NAMESPACE}" --from-literal=.dockerconfigjson="$DOCKER_CONFIG_JSON" --type=kubernetes.io/dockerconfigjson

    echo "Secret '${TARGET_SECRET_NAME}' created successfully."
---
apiVersion: batch/v1
kind: Job
metadata:
  name: copy-pull-secret-job
  namespace: open-cluster-management-observability
  annotations:
    argocd.argoproj.io/sync-wave: "9"
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded,BeforeHookCreation
spec:
  template:
    spec:
      serviceAccountName: thanos-tmp-sa
      restartPolicy: OnFailure
      automountServiceAccountToken: true
      containers:
        - name: copy-pull-secret-executor
          image: {{ .Values.acm.observability.jobimage | default "quay.io/validatedpatterns/imperative-container:v1" }}
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
            - /scripts/copy-pull-secret.sh
          volumeMounts:
            - name: script-volume
              mountPath: /scripts
      volumes:
        - name: script-volume
          configMap:
            name: copy-pull-secret
            defaultMode: 0755
{{- end }}
