{{- if .Values.acm.observability.enabled }}
apiVersion: observability.open-cluster-management.io/v1beta2
kind: MultiClusterObservability
metadata:
  name: observability
  annotations:
    argocd.argoproj.io/sync-wave: "11"
{{- if .Values.acm.observability.annotations }}
{{- toYaml .Values.acm.observability.annotations | nindent 4 }}
{{- end }}
spec:
# All below values are the default values
  instanceSize: {{ .Values.acm.observability.instansesize | default default}}
  enableDownsampling: true
  imagePullPolicy: Always
  imagePullSecret: multiclusterhub-operator-pull-secret
  observabilityAddonSpec: {}
  storageConfig:
    {{- if .Values.acm.observability.storageclass }}
    storageClass: {{ .Values.acm.observability.storageclass }}
    {{- end }}
    storeStorageSize: 10Gi
    metricObjectStorage:
      name: thanos-object-storage
      key: thanos.yaml
    writeStorage: []
    alertmanagerStorageSize: 1Gi
    compactStorageSize: 100Gi
    receiveStorageSize: 100Gi
    ruleStorageSize: 30Gi
  advanced:
    retentionConfig:
      blockDuration: 2h
      deleteDelay: 48h
      retentionInLocal: {{ .Values.acm.observability.retentionInLocal | default 24h }}
      retentionResolutionRaw: {{ .Values.acm.observability.retentionResolutionRaw | default 30d }}
      retentionResolution5m: {{ .Values.acm.observability.retentionResolution5m | default 180d }}
      retentionResolution1h: {{ .Values.acm.observability.retentionResolution1h | default 365d }}
{{- end }}
