{{- if .Values.acm.observability.enabled }}
apiVersion: observability.open-cluster-management.io/v1beta2
kind: MultiClusterObservability
metadata:
  name: observability
  annotations:
    argocd.argoproj.io/sync-wave: "11"
{{- if .Values.acm.observability.annotations }}
{{- toYaml .Values.acm.observability.annotations | nindent 4 }}
{{- end }}
spec:
  observabilityAddonSpec: {}
  storageConfig:
    metricObjectStorage:
      name: thanos-object-storage
      key: thanos.yaml
  advanced:
    retentionConfig:
      retentionResolutionRaw: 30d
      retentionResolution1h: 365d
      retentionInLocal: 48h
{{- end }}
