{{- if .Values.acm.observability.enabled }}
apiVersion: observability.open-cluster-management.io/v1beta2
kind: MultiClusterObservability
metadata:
  name: observability
  annotations:
    mco-disable-alerting="true"
spec:
  observabilityAddonSpec: {}
  storageConfig:
    storageClass: infra
    metricObjectStorage:
      name: thanos-object-storage
      key: thanos.yaml
{{- end }}
