odf:
  namespace: openshift-storage
  serviceUrl: "http://rook-ceph-rgw-ocs-storagecluster-cephobjectstore.openshift-storage.svc.cluster.local"
  externalUrl: "https://s3-rgw-openshift-storage"
  enable_mirroring: false

  osd:
    pvc:
      storage: 2Ti
    count: 1

  storageClass:
    name: ocs-storagecluster-ceph-rgw
    objectStoreName: ocs-storagecluster-cephobjectstore

  mon:
    requests: {}
  mds:
    requests: {}
  mgr:
    requests: {}
  noobaacore:
    requests: {}
  noobaadb:
    requests: {} 

route:
  name: s3-rgw
  service:
    name: rook-ceph-rgw-ocs-storagecluster-cephobjectstore
    weight: 100
  port:
    targetPort: http

#Define the CephObjectStorage parameters. RGW

objectStorage:
  enable: false
  dataPool:
    replicas: 3
    # -- Failuredomain for the dataPool
    failureDomain: host
  metadataPool:
    # -- Failuredomain for the metadataPool
    failureDomain: host
  gateway:
    instances: 2
  resources:
    requests: {}
    limits: {}  
    
#Define the odf storageSystem parameters

storageSystem:
  inventory:
    nodeJobLabelSelector: 'node-role.kubernetes.io/master='
    useSpecificNodes: false # true/false to label a specific set of nodes to be part of ODF
    #nodes:
    #- 
    #- 

#RoleBasedAccessControl

serviceAccountName: odf-node-label-sa
rbac:
  roles:
    - name: label-storage-nodes
      createRole: true
      apiGroups:
        - '""'
      scope:
        cluster: true
      resources:
        - nodes
      verbs:
        - "get"
        - "list"
        - "patch"
        - "update"
  roleBindings:
    - name: label-storage-nodes
      createBinding: true
      scope:
        cluster: true
        namespace: ""
      subjects:
        kind: ServiceAccount
        name: odf-node-label-sa
        namespace: openshift-storage
        apiGroup: ""
      roleRef:
        kind: ClusterRole
        name: label-storage-nodes
job:
  image: quay.io/validatedpatterns/imperative-container:v1


