acm:
  # In disconnected mode ONLY
  disconnected: false
  catalogsource: "redhat-operators"
  
  # Quay-enterprise details
  quayregistryurl:
  quaycabundle:
  
  # To update AgentService
  osimages:
    - cpuArchitecture: "x86_64"
      openshiftVersion: "4.20"
      # URLs for iso and rootfs files for Baremetal CWL deployments
      rootFSUrl: "http://<http-server-address:port>/rhcos-4.20.0-x86_64-live-rootfs.x86_64.img"
      url: "http://<http-server-address:port>/rhcos-4.20.0-x86_64-live-iso.x86_64.iso"
      version: "9.6.20250530-0"
  # Add new entries for new versions


  observability:
    enabled: true
    jobimage: quay.io/validatedpatterns/imperative-container:v1
    storageclass: infra
    annotations:
      mco-disable-alerting="true"
      
