apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: infra
  namespace: openshift-storage
spec:
  mirroring: {}
  compressionMode: none
  parameters:
    compression_mode: none
  erasureCoded:
    codingChunks: 0
    dataChunks: 0
  failureDomain: host
  application: ''
  enableCrushUpdates: true
  statusCheck:
    mirror: {}
  replicated:
    size: 3
    targetSizeRatio: 0.1
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: infra
parameters:
  clusterID: openshift-storage
  csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/controller-expand-secret-namespace: openshift-storage
  csi.storage.k8s.io/fstype: ext4
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
  csi.storage.k8s.io/node-stage-secret-namespace: openshift-storage
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: openshift-storage
  imageFeatures: layering,deep-flatten,exclusive-lock,object-map,fast-diff
  imageFormat: "2"
  pool: infra
provisioner: openshift-storage.rbd.csi.ceph.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
