apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  namespace: {{ .Values.odf.namespace }}
  name: ocs-storagecluster
spec:
{{- if .Values.odf.enable_mirroring }}
  mirroring:
    enabled: true
{{- end }}
  resources: 
    mon:
      requests:
        cpu: {{ .Values.odf.mon.requests.cpu | default 1 | squote }}
        memory: {{ .Values.odf.mon.requests.memory | default 2Gi }}
    mds:
      requests:
        cpu: {{ .Values.odf.mds.requests.cpu | default 3 | squote }}
        memory: {{ .Values.odf.mds.requests.memory | default 8Gi }}
    mgr:
      requests:
        cpu: {{ .Values.odf.mgr.requests.cpu | default 1 | squote }}
        memory: {{ .Values.odf.mgr.requests.memory | default 3Gi }}
    noobaa-core:
      requests:
        cpu: {{ .Values.odf.noobaacore.requests.cpu | default 1 | squote }}
        memory: {{ .Values.odf.noobaacore.requests.memory | default 4Gi }}
    noobaa-db:
      requests:
        cpu: {{ .Values.odf.noobaadb.requests.cpu | default 1 | squote }}
        memory: {{ .Values.odf.noobaadb.requests.memory | default 4Gi }}
  storageDeviceSets:
  - name: ocs-deviceset-localblock
    config: {}
    count: {{ .Values.odf.osd.count }}
    replica: 1
    resources: {}
#      requests:
#        cpu: {{ .Values.odf.osd.requests.cpu | squote }}
#        memory: {{ .Values.odf.osd.requests.memory }}
    placement: {}
    preparePlacement: {}
    dataPVCTemplate:
      metadata: {}
      spec:
        accessModes:
        - ReadWriteOnce
        volumeMode: Block
        storageClassName: localblock        
        resources:
          requests:
            storage: '1'
      status: {}
#    portable: true
  arbiter: {}
  enableCephTools: true
  encryption:
    kms: {}
  externalStorage: {}
  flexibleScaling: true
  managedResources:
    cephBlockPools: {}
    cephCluster: {}
    cephConfig: {}
    cephDashboard: {}
    cephFilesystems: {}
    cephNonResilientPools:
      count: 1
    cephObjectStoreUsers: {}
    cephObjectStores: {}
    cephRBDMirror:
      daemonCount: 1
    cephToolbox: {}
  mirroring: {}
  monDataDirHostPath: /var/lib/rook
  network:
    connections:
      encryption: {}
    multiClusterService: {}
    provider: multus
    selectors:
      cluster: openshift-storage/odf-cluster
      public: openshift-storage/odf-public
  nodeTopologies: {}
